Return-Path: <bpf-owner@vger.kernel.org>
X-Original-To: lists+bpf@lfdr.de
Delivered-To: lists+bpf@lfdr.de
Received: from out1.vger.email (out1.vger.email [IPv6:2620:137:e000::1:20])
	by mail.lfdr.de (Postfix) with ESMTP id 9F77A573921
	for <lists+bpf@lfdr.de>; Wed, 13 Jul 2022 16:45:10 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S235687AbiGMOpH (ORCPT <rfc822;lists+bpf@lfdr.de>);
        Wed, 13 Jul 2022 10:45:07 -0400
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:49586 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S235118AbiGMOpD (ORCPT <rfc822;bpf@vger.kernel.org>);
        Wed, 13 Jul 2022 10:45:03 -0400
Received: from linux.microsoft.com (linux.microsoft.com [13.77.154.182])
        by lindbergh.monkeyblade.net (Postfix) with ESMTP id E0EEF3A482;
        Wed, 13 Jul 2022 07:45:02 -0700 (PDT)
Received: from pwmachine.numericable.fr (240.119.92.79.rev.sfr.net [79.92.119.240])
        by linux.microsoft.com (Postfix) with ESMTPSA id E0FAB20B4774;
        Wed, 13 Jul 2022 07:44:59 -0700 (PDT)
DKIM-Filter: OpenDKIM Filter v2.11.0 linux.microsoft.com E0FAB20B4774
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=linux.microsoft.com;
        s=default; t=1657723502;
        bh=rLHlxm1tSrJ3VlsZpR5hKd+jJNry+nUsiNRAnBHf5Zw=;
        h=From:To:Cc:Subject:Date:In-Reply-To:References:From;
        b=Vv4I/sRm6MzL3f73RFru9M82S6MoxvYQys0LMpL/AuvD/fUZwh+YvOF6CLLLafT9s
         hJOmOu19pdX4u3ch39RA+tmPZNUiqLy1sJZ6LgxGt+w9GnOdsjuuzfxgaiUIJVsE5b
         RFOa450o67V25vQR2y1N3sg3rz2U6tSea5knHt08=
From:   Francis Laniel <flaniel@linux.microsoft.com>
To:     bpf@vger.kernel.org
Cc:     Francis Laniel <flaniel@linux.microsoft.com>,
        Quentin Monnet <quentin@isovalent.com>,
        Alexei Starovoitov <ast@kernel.org>,
        Daniel Borkmann <daniel@iogearbox.net>,
        Andrii Nakryiko <andrii@kernel.org>,
        Martin KaFai Lau <martin.lau@linux.dev>,
        Song Liu <song@kernel.org>, Yonghong Song <yhs@fb.com>,
        John Fastabend <john.fastabend@gmail.com>,
        KP Singh <kpsingh@kernel.org>,
        Stanislav Fomichev <sdf@google.com>,
        Hao Luo <haoluo@google.com>, Jiri Olsa <jolsa@kernel.org>,
        linux-kernel@vger.kernel.org (open list)
Subject: [PATCH v3 1/1] bpftool: Align dumped file generated header with skeletons.
Date:   Wed, 13 Jul 2022 16:44:38 +0200
Message-Id: <20220713144439.19738-2-flaniel@linux.microsoft.com>
X-Mailer: git-send-email 2.25.1
In-Reply-To: <20220713144439.19738-1-flaniel@linux.microsoft.com>
References: <20220713144439.19738-1-flaniel@linux.microsoft.com>
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit
X-Spam-Status: No, score=-19.8 required=5.0 tests=BAYES_00,DKIM_SIGNED,
        DKIM_VALID,DKIM_VALID_AU,ENV_AND_HDR_SPF_MATCH,RCVD_IN_DNSWL_MED,
        SPF_HELO_PASS,SPF_PASS,T_SCC_BODY_TEXT_LINE,USER_IN_DEF_DKIM_WL,
        USER_IN_DEF_SPF_WL autolearn=ham autolearn_force=no version=3.4.6
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on
        lindbergh.monkeyblade.net
Precedence: bulk
List-ID: <bpf.vger.kernel.org>
X-Mailing-List: bpf@vger.kernel.org

This commit adds the following lines to file generated by dump:
/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */
/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
Hence, the dumped file headers follows that of skeletons.

Signed-off-by: Francis Laniel <flaniel@linux.microsoft.com>
---
 tools/bpf/bpftool/btf.c | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/tools/bpf/bpftool/btf.c b/tools/bpf/bpftool/btf.c
index 7e6accb9d9f7..066a0acd0ecd 100644
--- a/tools/bpf/bpftool/btf.c
+++ b/tools/bpf/bpftool/btf.c
@@ -425,6 +425,8 @@ static int dump_btf_c(const struct btf *btf,
 	if (err)
 		return err;
 
+	printf("/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */\n");
+	printf("/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */\n");
 	printf("#ifndef __VMLINUX_H__\n");
 	printf("#define __VMLINUX_H__\n");
 	printf("\n");
-- 
2.25.1

